// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var Menu = require("./Menu.bs.js");
var Route = require("./Route.bs.js");
var React = require("react");
var LogoSvg = require("./logo.svg");
var ReasonReact = require("reason-react/src/ReasonReact.js");

((require('./app.css')));

var logo = LogoSvg;

var component = ReasonReact.statelessComponent("App");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", {
                          className: "App"
                        }, ReasonReact.element(undefined, undefined, Route.make(/* array */[])), ReasonReact.element(undefined, undefined, Menu.make(/* array */[])));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.logo = logo;
exports.component = component;
exports.make = make;
/*  Not a pure module */
