// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var Utils = require("./Utils.bs.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("YourEvents");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", undefined, React.createElement("div", {
                              className: "container mx-auto w-full py-10 tems-stretch"
                            }, React.createElement("div", {
                                  className: "w-full py-4"
                                }, React.createElement("div", {
                                      className: "p-4"
                                    }, React.createElement("h1", {
                                          className: "py-4 font-mono text-orange-dark"
                                        }, Utils.str("Create event"))), React.createElement("p", {
                                      className: "px-4"
                                    }, Utils.str("Create events for your club or by yourself. Items marked with asterisk must be filled."))), React.createElement("div", {
                                  className: "flex flex-wrap p-4"
                                }, React.createElement("div", {
                                      className: "sm:w-1/2 w-full mb-4"
                                    }, React.createElement("div", {
                                          className: "sm:p-3"
                                        }, React.createElement("p", {
                                              className: "text-left pb-2"
                                            }, Utils.str("Event Name *")), React.createElement("input", {
                                              className: "flex flex-wrap w-full  leading-normal w-px border h-10 border-grey-light rounded px-3  focus:border-blue focus:shadow",
                                              name: "name",
                                              placeholder: "Event Name",
                                              type: "text"
                                            }))), React.createElement("div", {
                                      className: "sm:w-1/2 w-full mb-4"
                                    }, React.createElement("div", {
                                          className: "sm:p-3"
                                        }, React.createElement("p", {
                                              className: "text-left pb-2"
                                            }, Utils.str("Host *")), React.createElement("input", {
                                              className: "flex flex-wrap w-full  leading-normal w-px border h-10 border-grey-light rounded px-3  focus:border-blue focus:shadow",
                                              name: "name",
                                              placeholder: "Host name",
                                              type: "text"
                                            }))), React.createElement("div", {
                                      className: "sm:w-1/3 w-full mb-4"
                                    }, React.createElement("div", {
                                          className: "sm:p-3"
                                        }, React.createElement("p", {
                                              className: "text-left pb-2"
                                            }, Utils.str("Start time *")), React.createElement("input", {
                                              className: "flex flex-wrap w-full  leading-normal w-px border h-10 border-grey-light rounded px-3  focus:border-blue focus:shadow",
                                              name: "name",
                                              placeholder: "Start time",
                                              type: "time"
                                            }))), React.createElement("div", {
                                      className: "sm:w-1/3 w-full mb-4"
                                    }, React.createElement("div", {
                                          className: "sm:p-3"
                                        }, React.createElement("p", {
                                              className: "text-left pb-2"
                                            }, Utils.str("End time *")), React.createElement("input", {
                                              className: "flex flex-wrap w-full  leading-normal w-px border h-10 border-grey-light rounded px-3  focus:border-blue focus:shadow",
                                              name: "name",
                                              placeholder: "End time",
                                              type: "time"
                                            }))), React.createElement("div", {
                                      className: "sm:w-1/3 w-full mb-4"
                                    }, React.createElement("div", {
                                          className: "sm:p-3"
                                        }, React.createElement("p", {
                                              className: "text-left pb-2"
                                            }, Utils.str("Date *")), React.createElement("input", {
                                              className: "flex flex-wrap w-full  leading-normal w-px border h-10 border-grey-light rounded px-3  focus:border-blue focus:shadow",
                                              name: "name",
                                              placeholder: "Date time",
                                              type: "date"
                                            }))), React.createElement("div", {
                                      className: "w-full mb-4"
                                    }, React.createElement("div", {
                                          className: "sm:p-3"
                                        }, React.createElement("p", {
                                              className: "text-left pb-2"
                                            }, Utils.str("Location *")), React.createElement("input", {
                                              className: "flex flex-wrap w-full  leading-normal w-px border h-10 border-grey-light rounded px-3  focus:border-blue focus:shadow",
                                              name: "name",
                                              placeholder: "Location",
                                              type: "text"
                                            }))), React.createElement("div", {
                                      className: "sm:w-1/2 w-full mb-4"
                                    }, React.createElement("div", {
                                          className: "sm:p-3"
                                        }, React.createElement("p", {
                                              className: "text-left pb-2"
                                            }, Utils.str("Latitude")), React.createElement("input", {
                                              className: "flex flex-wrap w-full  leading-normal w-px border h-10 border-grey-light rounded px-3  focus:border-blue focus:shadow",
                                              name: "name",
                                              placeholder: "Latitude",
                                              type: "number"
                                            }))), React.createElement("div", {
                                      className: "sm:w-1/2 w-full mb-4"
                                    }, React.createElement("div", {
                                          className: "sm:p-3"
                                        }, React.createElement("p", {
                                              className: "text-left pb-2"
                                            }, Utils.str("Longitude")), React.createElement("input", {
                                              className: "flex flex-wrap w-full  leading-normal w-px border h-10 border-grey-light rounded px-3  focus:border-blue focus:shadow",
                                              name: "name",
                                              placeholder: "Longitude",
                                              type: "number"
                                            }))), React.createElement("div", {
                                      className: "w-full mb-4"
                                    }, React.createElement("div", {
                                          className: "sm:p-3"
                                        }, React.createElement("p", {
                                              className: "text-left pb-2"
                                            }, Utils.str("Description")), React.createElement("input", {
                                              className: "flex flex-wrap w-full  leading-normal w-px border h-10 border-grey-light rounded px-3  focus:border-blue focus:shadow",
                                              name: "name",
                                              placeholder: "Description",
                                              type: "text"
                                            }))), React.createElement("div", {
                                      className: "w-full mb-4"
                                    }, React.createElement("div", {
                                          className: "sm:p-3"
                                        }, React.createElement("p", {
                                              className: "text-left pb-2"
                                            }, Utils.str("Facebook link")), React.createElement("input", {
                                              className: "flex flex-wrap w-full  leading-normal w-px border h-10 border-grey-light rounded px-3  focus:border-blue focus:shadow",
                                              name: "name",
                                              placeholder: "Facebook",
                                              type: "text"
                                            }))), React.createElement("div", {
                                      className: "flex items-center justify-center w-full"
                                    }, React.createElement("button", {
                                          className: "block bg-orange-dark hover:bg-teal text-white font-bold py-2 px-4 rounded"
                                        }, Utils.str("Create event"))))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
