// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var Utils = require("./Utils.bs.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Home");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", {
                          className: "container mx-auto w-full py-10 flex flex-wrap items-stretch"
                        }, React.createElement("div", {
                              className: "w-full text-center py-4"
                            }, React.createElement("div", {
                                  className: "py-4"
                                }, React.createElement("h1", {
                                      className: "py-4"
                                    }, Utils.str("Welcome to Monash Party Finder, Harry")), React.createElement("p", {
                                      className: ""
                                    }, Utils.str("There are lots of great events coming up this week! Here are a selection of the events coming up this week based on your subscriptions.")), React.createElement("p", {
                                      className: "pb-4"
                                    }, Utils.str("You have subscribed to the following topics:")), React.createElement("span", {
                                      className: "inline-block bg-grey-lighter rounded-full px-3 py-1 text-sm font-semibold text-grey-darker mr-2"
                                    }, Utils.str("#social")), React.createElement("span", {
                                      className: "inline-block bg-grey-lighter rounded-full px-3 py-1 text-sm font-semibold text-grey-darker mr-2"
                                    }, Utils.str("#academic")), React.createElement("span", {
                                      className: "inline-block bg-grey-lighter rounded-full px-3 py-1 text-sm font-semibold text-grey-darker"
                                    }, Utils.str("#free-food")))), React.createElement("div", {
                              className: "md:w-1/3 overflow-hidden  w-full p-4"
                            }, React.createElement("img", {
                                  className: "w-full",
                                  alt: "Sunset in the mountains",
                                  src: "https://tailwindcss.com/img/card-top.jpg"
                                }), React.createElement("div", {
                                  className: "px-6 py-4 border border-grey-light"
                                }, React.createElement("div", {
                                      className: "font-bold text-xl mb-2"
                                    }, Utils.str("The coldest sunset")), React.createElement("p", {
                                      className: "text-grey-darker text-base"
                                    }, Utils.str("this is a bunch of text lalallalalalala"))), React.createElement("div", {
                                  className: "px-6 py-4"
                                }, React.createElement("span", {
                                      className: "inline-block bg-grey-lighter rounded-full px-3 py-1 text-sm font-semibold text-grey-darker mr-2"
                                    }, Utils.str("#photo")), React.createElement("span", {
                                      className: "inline-block bg-grey-lighter rounded-full px-3 py-1 text-sm font-semibold text-grey-darker mr-2"
                                    }, Utils.str("#travel")), React.createElement("span", {
                                      className: "inline-block bg-grey-lighter rounded-full px-3 py-1 text-sm font-semibold text-grey-darker"
                                    }, Utils.str("#winter")))), React.createElement("div", {
                              className: "md:w-1/3 overflow-hidden border border-grey-light w-full p-4"
                            }, React.createElement("img", {
                                  className: "w-full",
                                  alt: "Sunset in the mountains",
                                  src: "https://tailwindcss.com/img/card-top.jpg"
                                }), React.createElement("div", {
                                  className: "px-6 py-4 border border-grey-light"
                                }, React.createElement("div", {
                                      className: "font-bold text-xl mb-2"
                                    }, Utils.str("The coldest sunset")), React.createElement("p", {
                                      className: "text-grey-darker text-base"
                                    }, Utils.str("this is a bunch of text lalallalalalala"))), React.createElement("div", {
                                  className: "px-6 py-4"
                                }, React.createElement("span", {
                                      className: "inline-block bg-grey-lighter rounded-full px-3 py-1 text-sm font-semibold text-grey-darker mr-2"
                                    }, Utils.str("#photo")), React.createElement("span", {
                                      className: "inline-block bg-grey-lighter rounded-full px-3 py-1 text-sm font-semibold text-grey-darker mr-2"
                                    }, Utils.str("#travel")), React.createElement("span", {
                                      className: "inline-block bg-grey-lighter rounded-full px-3 py-1 text-sm font-semibold text-grey-darker"
                                    }, Utils.str("#winter")))), React.createElement("div", {
                              className: "md:w-1/3 overflow-hidden border border-grey-light w-full p-4"
                            }, React.createElement("img", {
                                  className: "w-full",
                                  alt: "Sunset in the mountains",
                                  src: "https://tailwindcss.com/img/card-top.jpg"
                                }), React.createElement("div", {
                                  className: "px-6 py-4 border border-grey-light"
                                }, React.createElement("div", {
                                      className: "font-bold text-xl mb-2"
                                    }, Utils.str("The coldest sunset")), React.createElement("p", {
                                      className: "text-grey-darker text-base"
                                    }, Utils.str("this is a bunch of text lalallalalalala"))), React.createElement("div", {
                                  className: "px-6 py-4"
                                }, React.createElement("span", {
                                      className: "inline-block bg-grey-lighter rounded-full px-3 py-1 text-sm font-semibold text-grey-darker mr-2"
                                    }, Utils.str("#photo")), React.createElement("span", {
                                      className: "inline-block bg-grey-lighter rounded-full px-3 py-1 text-sm font-semibold text-grey-darker mr-2"
                                    }, Utils.str("#travel")), React.createElement("span", {
                                      className: "inline-block bg-grey-lighter rounded-full px-3 py-1 text-sm font-semibold text-grey-darker"
                                    }, Utils.str("#winter")))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
