// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var Utils = require("./Utils.bs.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Home");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", {
                          className: "container mx-auto w-full py-10 flex flex-wrap items-stretch"
                        }, React.createElement("div", {
                              className: "w-full text-center py-4"
                            }, React.createElement("div", {
                                  className: "p-4"
                                }, React.createElement("h1", {
                                      className: "py-4"
                                    }, Utils.str("Welcome to Monash Party Finder, Harry")), React.createElement("p", {
                                      className: ""
                                    }, Utils.str("There are lots of great events coming up this week! Here are a selection of the events coming up this week based on your subscriptions.")), React.createElement("p", {
                                      className: "pb-4"
                                    }, Utils.str("You have subscribed to the following topics:")), React.createElement("span", {
                                      className: "inline-block bg-orange-lighter rounded-full px-3 py-1 text-sm font-semibold text-grey-darker  mr-2 mt-2"
                                    }, Utils.str("#social")), React.createElement("span", {
                                      className: "inline-block bg-orange-lighter rounded-full px-3 py-1 text-sm font-semibold text-grey-darker  mr-2 mt-2"
                                    }, Utils.str("#academic")), React.createElement("span", {
                                      className: "inline-block bg-orange-lighter rounded-full px-3 py-1 text-sm font-semibold text-grey-darker"
                                    }, Utils.str("#free-food")))), React.createElement("div", {
                              className: "md:w-1/3 overflow-hidden w-full p-4"
                            }, React.createElement("div", {
                                  className: "border border-grey-light"
                                }, React.createElement("img", {
                                      className: "h-48",
                                      alt: "Sunset in the mountains",
                                      src: "https://scontent.fcbr1-1.fna.fbcdn.net/v/t1.0-9/28059157_946979332131457_7165184541920598166_n.jpg?_nc_cat=109&_nc_ht=scontent.fcbr1-1.fna&oh=5a6594412643437b10c91ba3e8816b7f&oe=5D3E8D49"
                                    }), React.createElement("div", {
                                      className: "px-6 py-4"
                                    }, React.createElement("div", {
                                          className: "font-bold text-xl mb-2"
                                        }, Utils.str("Monash NZSA Trivia Night")), React.createElement("p", {
                                          className: "text-grey-darker text-base"
                                        }, Utils.str("Sun, Apr 7, 12:00pm-14:00pm")), React.createElement("p", {
                                          className: "text-grey-darker text-base py-2"
                                        }, Utils.str("E359, 20 Chancellors Walk"))), React.createElement("div", {
                                      className: "px-6 py-4"
                                    }, React.createElement("span", {
                                          className: "inline-block bg-orange-lighter rounded-full px-3 py-1 text-sm font-semibold text-grey-darker  mr-2 mt-2"
                                        }, Utils.str("#hello")), React.createElement("span", {
                                          className: "inline-block bg-orange-lighter rounded-full px-3 py-1 text-sm font-semibold text-grey-darker  mr-2 mt-2"
                                        }, Utils.str("#cultural"))))), React.createElement("div", {
                              className: "md:w-1/3 overflow-hidden w-full p-4"
                            }, React.createElement("div", {
                                  className: "border border-grey-light"
                                }, React.createElement("img", {
                                      className: "h-48",
                                      alt: "Sunset in the mountains",
                                      src: "https://www.monashclubs.org/CMSModules/Avatars/CMSPages/GetAvatar.aspx?avatarguid=bda7da3e-79c2-4043-a601-c3ec064bb96a&maxsidesize=200"
                                    }), React.createElement("div", {
                                      className: "px-6 py-4"
                                    }, React.createElement("div", {
                                          className: "font-bold text-xl mb-2"
                                        }, Utils.str("The Timeless Miracle with Br Jafar Hussain")), React.createElement("p", {
                                          className: "text-grey-darker text-base"
                                        }, Utils.str("Sun, Apr 7, 12:00pm-14:00pm")), React.createElement("p", {
                                          className: "text-grey-darker text-base py-2"
                                        }, Utils.str("S1 Lecture Theatre, 16 Rainforest Walk"))), React.createElement("div", {
                                      className: "px-6 py-4"
                                    }, React.createElement("span", {
                                          className: "inline-block bg-orange-lighter rounded-full px-3 py-1 text-sm font-semibold text-grey-darker  mr-2 mt-2"
                                        }, Utils.str("#social")), React.createElement("span", {
                                          className: "inline-block bg-orange-lighter rounded-full px-3 py-1 text-sm font-semibold text-grey-darker  mr-2 mt-2"
                                        }, Utils.str("#paid")), React.createElement("span", {
                                          className: "inline-block bg-orange-lighter rounded-full px-3 py-1 text-sm font-semibold text-grey-darker  mr-2 mt-2"
                                        }, Utils.str("#competitive"))))), React.createElement("div", {
                              className: "md:w-1/3 overflow-hidden w-full p-4"
                            }, React.createElement("div", {
                                  className: "border border-grey-light"
                                }, React.createElement("img", {
                                      className: "h-48",
                                      alt: "Sunset in the mountains",
                                      src: "https://www.monashclubs.org/CMSModules/Avatars/CMSPages/GetAvatar.aspx?avatarguid=15e8b216-7b22-4d76-90dc-b7bebd32d0db&maxsidesize=200"
                                    }), React.createElement("div", {
                                      className: "px-6 py-4"
                                    }, React.createElement("div", {
                                          className: "font-bold text-xl mb-2"
                                        }, Utils.str("Oragami Night")), React.createElement("p", {
                                          className: "text-grey-darker text-base"
                                        }, Utils.str("Sun, Apr 7, 12:00pm-14:00pm")), React.createElement("p", {
                                          className: "text-grey-darker text-base py-2"
                                        }, Utils.str("Japanese Studies Centre Auditorium"))), React.createElement("div", {
                                      className: "px-6 py-4"
                                    }, React.createElement("span", {
                                          className: "inline-block bg-orange-lighter rounded-full px-3 py-1 text-sm font-semibold text-grey-darker  mr-2 mt-2"
                                        }, Utils.str("#social")), React.createElement("span", {
                                          className: "inline-block bg-orange-lighter rounded-full px-3 py-1 text-sm font-semibold text-grey-darker  mr-2 mt-2"
                                        }, Utils.str("#culture")), React.createElement("span", {
                                          className: "inline-block bg-orange-lighter rounded-full px-3 py-1 text-sm font-semibold text-grey-darker  mr-2 mt-2"
                                        }, Utils.str("#free-food"))))), React.createElement("div", {
                              className: "md:w-1/3 overflow-hidden w-full p-4"
                            }, React.createElement("div", {
                                  className: "border border-grey-light"
                                }, React.createElement("img", {
                                      className: "h-48",
                                      alt: "Sunset in the mountains",
                                      src: "https://www.monashclubs.org/CMSModules/Avatars/CMSPages/GetAvatar.aspx?avatarguid=41671f9b-2184-4fb2-bb4e-92f1683a0d74&maxsidesize=200"
                                    }), React.createElement("div", {
                                      className: "px-6 py-4"
                                    }, React.createElement("div", {
                                          className: "font-bold text-xl mb-2"
                                        }, Utils.str("Tech Industry Night")), React.createElement("p", {
                                          className: "text-grey-darker text-base"
                                        }, Utils.str("un, Apr 7, 12:00pm-14:00pm")), React.createElement("p", {
                                          className: "text-grey-darker text-base py-2"
                                        }, Utils.str("Campus Centre"))), React.createElement("div", {
                                      className: "px-6 py-4"
                                    }, React.createElement("span", {
                                          className: "inline-block bg-orange-lighter rounded-full px-3 py-1 text-sm font-semibold text-grey-darker  mr-2 mt-2"
                                        }, Utils.str("#social")), React.createElement("span", {
                                          className: "inline-block bg-orange-lighter rounded-full px-3 py-1 text-sm font-semibold text-grey-darker  mr-2 mt-2"
                                        }, Utils.str("#academic")), React.createElement("span", {
                                          className: "inline-block bg-orange-lighter rounded-full px-3 py-1 text-sm font-semibold text-grey-darker  mr-2 mt-2"
                                        }, Utils.str("#free-food"))))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
