// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var Utils = require("./Utils.bs.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Home");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", {
                          className: "App"
                        }, React.createElement("div", {
                              className: "container mx-auto h-full flex justify-center items-center"
                            }, React.createElement("div", {
                                  className: "w-1/2 text-center py-4"
                                }, React.createElement("h1", {
                                      className: "font-hairline mb-6 text-center"
                                    }, Utils.str("Login to Party Finder")), React.createElement("div", {
                                      className: "border-teal p-8 border-t-12 bg-white mb-6 rounded-lg shadow-lg"
                                    }, React.createElement("div", {
                                          className: "mb-4"
                                        }, React.createElement("label", {
                                              className: "font-bold text-grey-darker block mb-2"
                                            }, Utils.str("Username or Email")), React.createElement("input", {
                                              className: "block appearance-none w-full bg-white border border-grey-light hover:border-grey px-2 py-2 rounded shadow",
                                              placeholder: "Your Username",
                                              type: "text"
                                            })), React.createElement("div", {
                                          className: "mb-4"
                                        }, React.createElement("label", {
                                              className: "font-bold text-grey-darker block mb-2"
                                            }, Utils.str("Password")), React.createElement("input", {
                                              className: "block appearance-none w-full bg-white border border-grey-light hover:border-grey px-2 py-2 rounded shadow",
                                              placeholder: "Password",
                                              type: "text"
                                            })), React.createElement("div", {
                                          className: "flex items-center justify-center"
                                        }, React.createElement("button", {
                                              className: "block bg-teal-dark hover:bg-teal text-white font-bold py-2 px-4 rounded"
                                            }, Utils.str("Login")))))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
