// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var App = require("./app.bs.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Utils = require("./Utils.bs.js");
var React = require("react");
var UserData = require("./UserData.bs.js");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.reducerComponent("Login");

function reducer(action, state) {
  switch (action.tag | 0) {
    case 0 : 
        var params = action[1];
        var method_ = action[0];
        return /* SideEffects */Block.__(1, [(function (self) {
                      return UserData.fetchData(method_, params, UserData.Decode[/* getLoginValidation */2], state, (function (payload) {
                                    return Curry._1(self[/* send */3], /* Fetched */Block.__(1, [payload]));
                                  }));
                    })]);
    case 1 : 
        var payload = action[0][1];
        var match = payload[/* validation */0] === 0;
        return /* UpdateWithSideEffects */Block.__(2, [
                  /* record */[
                    /* username */state[/* username */0],
                    /* password */state[/* password */1],
                    /* userId */String(payload[/* validation */0]),
                    /* loginError */match ? "Invalid Login Details" : ""
                  ],
                  (function (self) {
                      var match = self[/* state */1][/* loginError */3] === "";
                      if (match) {
                        ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, App.make(self[/* state */1][/* userId */2], /* array */[])), "root");
                        return ReasonReact.Router[/* push */0]("/home");
                      } else {
                        return /* () */0;
                      }
                    })
                ]);
    case 2 : 
        return /* Update */Block.__(0, [/* record */[
                    /* username */action[0],
                    /* password */state[/* password */1],
                    /* userId */state[/* userId */2],
                    /* loginError */state[/* loginError */3]
                  ]]);
    case 3 : 
        return /* Update */Block.__(0, [/* record */[
                    /* username */state[/* username */0],
                    /* password */action[0],
                    /* userId */state[/* userId */2],
                    /* loginError */state[/* loginError */3]
                  ]]);
    
  }
}

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */1][/* loginError */3] === "";
              return React.createElement("div", {
                          className: ""
                        }, React.createElement("div", {
                              className: "container mx-auto h-full w-full flex justify-center align-middle items-center"
                            }, React.createElement("div", {
                                  className: "md:w-1/2 w-3/4 text-center py-4"
                                }, React.createElement("img", {
                                      src: "https://scontent.fcbr1-1.fna.fbcdn.net/v/t1.15752-0/p280x280/56966759_1271879692960761_6424104639007817728_n.png?_nc_cat=108&_nc_ht=scontent.fcbr1-1.fna&oh=14c3fe43347abfd84770679a3faf1fbc&oe=5D4F37CC"
                                    }), React.createElement("h1", {
                                      className: "font-hairline mb-6 text-center"
                                    }, Utils.str("Login to MONTEA")), React.createElement("div", {
                                      className: "border-orange p-8 border-t-12 bg-white mb-6 rounded-lg shadow-lg"
                                    }, match ? React.createElement("p", undefined) : React.createElement("p", {
                                            className: "font-sans text-lg text-red-dark text-center"
                                          }, Utils.str("Invalid login details")), React.createElement("div", {
                                          className: "mb-4"
                                        }, React.createElement("label", {
                                              className: "font-bold text-grey-darker block mb-2"
                                            }, Utils.str("Username")), React.createElement("input", {
                                              className: "block appearance-none w-full bg-white border border-grey-light hover:border-grey px-2 py-2 rounded shadow",
                                              placeholder: "Username",
                                              type: "text",
                                              onChange: (function (e) {
                                                  return Curry._1(self[/* send */3], /* SetUsername */Block.__(2, [Utils.getValueFromEvent(e)]));
                                                })
                                            })), React.createElement("div", {
                                          className: "mb-4"
                                        }, React.createElement("label", {
                                              className: "font-bold text-grey-darker block mb-2"
                                            }, Utils.str("Password")), React.createElement("input", {
                                              className: "block appearance-none w-full bg-white border border-grey-light hover:border-grey px-2 py-2 rounded shadow",
                                              placeholder: "Password",
                                              type: "password",
                                              onChange: (function (e) {
                                                  return Curry._1(self[/* send */3], /* SetPassword */Block.__(3, [Utils.getValueFromEvent(e)]));
                                                })
                                            })), React.createElement("div", {
                                          className: "flex items-center justify-center"
                                        }, React.createElement("button", {
                                              className: "block bg-orange-dark hover:bg-orange text-white font-bold py-2 px-4 rounded",
                                              onClick: (function (_e) {
                                                  return Curry._1(self[/* send */3], /* Fetch */Block.__(0, [
                                                                "authenticate_user",
                                                                /* array */[
                                                                  self[/* state */1][/* username */0],
                                                                  self[/* state */1][/* password */1]
                                                                ]
                                                              ]));
                                                })
                                            }, Utils.str("Login")))))));
            }),
          /* initialState */(function (param) {
              return /* record */[
                      /* username */"",
                      /* password */"",
                      /* userId */"-1",
                      /* loginError */""
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */reducer,
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.reducer = reducer;
exports.make = make;
/* component Not a pure module */
