// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var Utils = require("./Utils.bs.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Map");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", {
                          className: "container mx-auto w-full py-10 tems-stretch"
                        }, React.createElement("div", {
                              className: "w-full py-4"
                            }, React.createElement("div", {
                                  className: "p-4 pb-6"
                                }, React.createElement("h1", {
                                      className: "py-4 font-mono text-orange-dark"
                                    }, Utils.str("Map")), React.createElement("p", undefined, Utils.str("Here is an interactive map of all the events currently happening at Monash, for more information, click on a marker to display the event information."))), React.createElement("div", undefined, React.createElement("img", {
                                      src: "https://i.imgur.com/yt4Uk8X.jpg"
                                    }))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
