// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Utils = require("./Utils.bs.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.reducerComponent("Menu");

function reducer(action, _state) {
  return /* Update */Block.__(0, [/* record */[/* clickedMenu */action[0]]]);
}

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */1][/* clickedMenu */0] === "Home";
              var match$1 = self[/* state */1][/* clickedMenu */0] === "ManageEvents";
              var match$2 = self[/* state */1][/* clickedMenu */0] === "CreateEvent";
              var match$3 = self[/* state */1][/* clickedMenu */0] === "Map";
              var match$4 = self[/* state */1][/* clickedMenu */0] === "Profile";
              return React.createElement("div", {
                          className: "w-full md:w-1/5 bg-black md:bg-black px-2 text-center fixed pin-b md:pt-8 md:pin-t md:pin-l h-16 md:h-screen md:border-r-4 md:border-grey-dark"
                        }, React.createElement("div", {
                              className: "md:relative mx-auto lg:float-right lg:px-6"
                            }, React.createElement("ul", {
                                  className: "list-reset flex flex-row md:flex-col text-center md:text-left"
                                }, React.createElement("li", {
                                      className: "mr-3 flex-1"
                                    }, React.createElement("a", {
                                          className: match ? "block py-1 md:py-3 pl-1 align-middle text-white no-underline border-b-2 border-orange-dark" : "block py-1 md:py-3 pl-1 align-middle text-grey-darkest no-underline hover:text-orange border-b-2 border-grey-darkest md:border-black hover:border-orange",
                                          href: "#",
                                          onClick: (function (_e) {
                                              ReasonReact.Router[/* push */0]("/home");
                                              return Curry._1(self[/* send */3], /* Clicked */["Home"]);
                                            })
                                        }, React.createElement("i", {
                                              className: "fas fa-home pr-0 md:pr-3"
                                            }), React.createElement("span", {
                                              className: "pb-1 md:pb-0 text-xs md:text-base text-grey-dark md:text-grey-light block md:inline-block"
                                            }, Utils.str("home")))), React.createElement("li", {
                                      className: "mr-3 flex-1"
                                    }, React.createElement("a", {
                                          className: match$1 ? "block py-1 md:py-3 pl-1 align-middle text-white no-underline border-b-2 border-orange-dark" : "block py-1 md:py-3 pl-1 align-middle text-grey-darkest no-underline hover:text-orange border-b-2 border-grey-darkest md:border-black hover:border-orange",
                                          href: "#",
                                          onClick: (function (_e) {
                                              ReasonReact.Router[/* push */0]("/manage-events");
                                              return Curry._1(self[/* send */3], /* Clicked */["ManageEvents"]);
                                            })
                                        }, React.createElement("i", {
                                              className: "fas fa-calendar-day pr-0 md:pr-3"
                                            }), React.createElement("span", {
                                              className: "pb-1 md:pb-0 text-xs md:text-base text-grey-dark md:text-grey-light block md:inline-block"
                                            }, Utils.str("Manage Events")))), React.createElement("li", {
                                      className: "mr-3 flex-1"
                                    }, React.createElement("a", {
                                          className: match$2 ? "block py-1 md:py-3 pl-1 align-middle text-white no-underline border-b-2 border-orange-dark" : "block py-1 md:py-3 pl-1 align-middle text-grey-darkest no-underline hover:text-orange border-b-2 border-grey-darkest md:border-black hover:border-orange",
                                          href: "#",
                                          onClick: (function (_e) {
                                              ReasonReact.Router[/* push */0]("/create-event");
                                              return Curry._1(self[/* send */3], /* Clicked */["CreateEvent"]);
                                            })
                                        }, React.createElement("i", {
                                              className: "fas fa-plus pr-0 md:pr-3"
                                            }), React.createElement("span", {
                                              className: "pb-1 md:pb-0 text-xs md:text-base text-grey-dark md:text-grey-light block md:inline-block"
                                            }, Utils.str("Create Events")))), React.createElement("li", {
                                      className: "mr-3 flex-1"
                                    }, React.createElement("a", {
                                          className: match$3 ? "block py-1 md:py-3 pl-1 align-middle text-white no-underline border-b-2 border-orange-dark" : "block py-1 md:py-3 pl-1 align-middle text-grey-darkest no-underline hover:text-orange border-b-2 border-grey-darkest md:border-black hover:border-orange",
                                          href: "#",
                                          onClick: (function (_e) {
                                              ReasonReact.Router[/* push */0]("/map");
                                              return Curry._1(self[/* send */3], /* Clicked */["Map"]);
                                            })
                                        }, React.createElement("i", {
                                              className: "fas fa-map-marked pr-0 md:pr-3"
                                            }), React.createElement("span", {
                                              className: "pb-1 md:pb-0 text-xs md:text-base text-grey-dark md:text-grey-light block md:inline-block"
                                            }, Utils.str("Map")))), React.createElement("li", {
                                      className: "mr-3 flex-1"
                                    }, React.createElement("a", {
                                          className: match$4 ? "block py-1 md:py-3 pl-1 align-middle text-white no-underline border-b-2 border-orange-dark" : "block py-1 md:py-3 pl-1 align-middle text-grey-darkest no-underline hover:text-orange border-b-2 border-grey-darkest md:border-black hover:border-orange",
                                          href: "#",
                                          onClick: (function (_e) {
                                              ReasonReact.Router[/* push */0]("/profile");
                                              return Curry._1(self[/* send */3], /* Clicked */["Profile"]);
                                            })
                                        }, React.createElement("i", {
                                              className: "fas fa-user pr-0 md:pr-3"
                                            }), React.createElement("span", {
                                              className: "pb-1 md:pb-0 text-xs md:text-base text-grey-dark md:text-grey-light block md:inline-block"
                                            }, Utils.str("Profile")))))));
            }),
          /* initialState */(function (param) {
              return /* record */[/* clickedMenu */"Home"];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */reducer,
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.reducer = reducer;
exports.make = make;
/* component Not a pure module */
