// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var Utils = require("./Utils.bs.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Menu");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", {
                          className: "w-full md:w-1/5 bg-black md:bg-black px-2 text-center fixed pin-b md:pt-8 md:pin-t md:pin-l h-16 md:h-screen md:border-r-4 md:border-grey-dark"
                        }, React.createElement("div", {
                              className: "md:relative mx-auto lg:float-right lg:px-6"
                            }, React.createElement("ul", {
                                  className: "list-reset flex flex-row md:flex-col text-center md:text-left"
                                }, React.createElement("li", {
                                      className: "mr-3 flex-1"
                                    }, React.createElement("a", {
                                          className: "block py-1 md:py-3 pl-1 align-middle text-grey-darkest no-underline hover:text-orange border-b-2 border-grey-darkest md:border-black hover:border-orange",
                                          href: "#"
                                        }, React.createElement("i", {
                                              className: "fas fa-home pr-0 md:pr-3"
                                            }), React.createElement("span", {
                                              className: "pb-1 md:pb-0 text-xs md:text-base text-grey-dark md:text-grey-light block md:inline-block"
                                            }, Utils.str("Home")))), React.createElement("li", {
                                      className: "mr-3 flex-1"
                                    }, React.createElement("a", {
                                          className: "block py-1 md:py-3 pl-1 align-middle text-grey-darkest no-underline hover:text-orange border-b-2 border-grey-darkest md:border-black hover:border-orange",
                                          href: "#"
                                        }, React.createElement("i", {
                                              className: "fas fa-calendar-day pr-0 md:pr-3"
                                            }), React.createElement("span", {
                                              className: "pb-1 md:pb-0 text-xs md:text-base text-grey-dark md:text-grey-light block md:inline-block"
                                            }, Utils.str("Your Events")))), React.createElement("li", {
                                      className: "mr-3 flex-1"
                                    }, React.createElement("a", {
                                          className: "block py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white border-b-2 border-orange-dark",
                                          href: "#"
                                        }, React.createElement("i", {
                                              className: "fas fa-map-marked pr-0 md:pr-3"
                                            }), React.createElement("span", {
                                              className: "pb-1 md:pb-0 text-xs md:text-base text-white md:font-bold block md:inline-block"
                                            }, Utils.str("Map")))), React.createElement("li", {
                                      className: "mr-3 flex-1"
                                    }, React.createElement("a", {
                                          className: "block py-1 md:py-3 pl-1 align-middle text-grey-darkest no-underline hover:text-orange border-b-2 border-grey-darkest md:border-black hover:border-orange",
                                          href: "#"
                                        }, React.createElement("i", {
                                              className: "fas fa-user pr-0 md:pr-3"
                                            }), React.createElement("span", {
                                              className: "pb-1 md:pb-0 text-xs md:text-base text-grey-dark md:text-grey-light block md:inline-block"
                                            }, Utils.str("Profile")))))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
