// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';


function str(prim) {
  return prim;
}

function getValueFromEvent($$event) {
  return $$event.target.value;
}

function getButtonValueFromEvent($$event) {
  return $$event.target.value;
}

function incrementId(i) {
  i[0] = i[0] + 1 | 0;
  return /* () */0;
}

exports.str = str;
exports.getValueFromEvent = getValueFromEvent;
exports.getButtonValueFromEvent = getButtonValueFromEvent;
exports.incrementId = incrementId;
/* No side effect */
