// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';


function str(prim) {
  return prim;
}

function getValueFromEvent($$event) {
  return $$event.target.value;
}

exports.str = str;
exports.getValueFromEvent = getValueFromEvent;
/* No side effect */
