// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var Utils = require("./Utils.bs.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("YourEvents");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", undefined, React.createElement("div", {
                              className: "container mx-auto w-full py-10 tems-stretch"
                            }, React.createElement("div", {
                                  className: "w-full py-4"
                                }, React.createElement("div", {
                                      className: "p-4"
                                    }, React.createElement("h1", {
                                          className: "py-4 font-mono text-orange-dark"
                                        }, Utils.str("Edit event"))), React.createElement("p", {
                                      className: "px-4"
                                    }, Utils.str("Edit your existing event to add more information."))), React.createElement("div", {
                                  className: "md:w-1/3 overflow-hidden w-full p-4"
                                }, React.createElement("div", {
                                      className: "border border-grey-light"
                                    }, React.createElement("img", {
                                          className: "h-48",
                                          alt: "montea logo",
                                          src: "https://scontent.fcbr1-1.fna.fbcdn.net/v/t1.15752-0/p280x280/56966759_1271879692960761_6424104639007817728_n.png?_nc_cat=108&_nc_ht=scontent.fcbr1-1.fna&oh=14c3fe43347abfd84770679a3faf1fbc&oe=5D4F37CC"
                                        }), React.createElement("div", {
                                          className: "px-6 py-4"
                                        }, React.createElement("div", {
                                              className: "font-bold text-xl mb-2"
                                            }, Utils.str("MonTEA official Launch")), React.createElement("p", {
                                              className: "text-grey-darker text-base"
                                            }, Utils.str("Sun, Apr 7, 12:00pm-14:00pm")), React.createElement("p", {
                                              className: "text-grey-darker text-base py-2"
                                            }, Utils.str("Kenneth Hunt Lawn"))), React.createElement("div", {
                                          className: "px-6 py-4"
                                        }, React.createElement("span", {
                                              className: "inline-block bg-orange-lighter rounded-full px-3 py-1 text-sm font-semibold text-grey-darker mr-2 mt-2"
                                            }, Utils.str("#social")), React.createElement("span", {
                                              className: "inline-block bg-orange-lighter rounded-full px-3 py-1 text-sm font-semibold text-grey-darker mr-2 mt-2"
                                            }, Utils.str("#culture")), React.createElement("span", {
                                              className: "inline-block bg-orange-lighter rounded-full px-3 py-1 text-sm font-semibold text-grey-darker mr-2 mt-2"
                                            }, Utils.str("#free-food"))))), React.createElement("div", {
                                  className: "flex flex-wrap p-4"
                                }, React.createElement("div", {
                                      className: "sm:w-1/2 w-full mb-4"
                                    }, React.createElement("div", {
                                          className: "sm:p-3"
                                        }, React.createElement("p", {
                                              className: "text-left pb-2"
                                            }, Utils.str("Event Name *")), React.createElement("input", {
                                              className: "flex flex-wrap w-full  leading-normal w-px border h-10 border-grey-light rounded px-3 focus:border-blue focus:shadow",
                                              name: "name",
                                              type: "text",
                                              value: "MonTEA's official launch"
                                            }))), React.createElement("div", {
                                      className: "sm:w-1/2 w-full mb-4"
                                    }, React.createElement("div", {
                                          className: "sm:p-3"
                                        }, React.createElement("p", {
                                              className: "text-left pb-2"
                                            }, Utils.str("Host *")), React.createElement("input", {
                                              className: "flex flex-wrap w-full  leading-normal w-px border h-10 border-grey-light rounded px-3 focus:border-blue focus:shadow",
                                              name: "name",
                                              type: "text",
                                              value: "MonTEA crew"
                                            }))), React.createElement("div", {
                                      className: "sm:w-1/3 w-full mb-4"
                                    }, React.createElement("div", {
                                          className: "sm:p-3"
                                        }, React.createElement("p", {
                                              className: "text-left pb-2"
                                            }, Utils.str("Start time *")), React.createElement("input", {
                                              className: "flex flex-wrap w-full  leading-normal w-px border h-10 border-grey-light rounded px-3  focus:border-blue focus:shadow",
                                              name: "name",
                                              type: "time",
                                              value: "12:00:00"
                                            }))), React.createElement("div", {
                                      className: "sm:w-1/3 w-full mb-4"
                                    }, React.createElement("div", {
                                          className: "sm:p-3"
                                        }, React.createElement("p", {
                                              className: "text-left pb-2"
                                            }, Utils.str("End time *")), React.createElement("input", {
                                              className: "flex flex-wrap w-full  leading-normal w-px border h-10 border-grey-light rounded px-3  focus:border-blue focus:shadow",
                                              name: "name",
                                              type: "time",
                                              value: "14:00:00"
                                            }))), React.createElement("div", {
                                      className: "sm:w-1/3 w-full mb-4"
                                    }, React.createElement("div", {
                                          className: "sm:p-3"
                                        }, React.createElement("p", {
                                              className: "text-left pb-2"
                                            }, Utils.str("Date *")), React.createElement("input", {
                                              className: "flex flex-wrap w-full  leading-normal w-px border h-10 border-grey-light rounded px-3  focus:border-blue focus:shadow",
                                              name: "name",
                                              type: "date",
                                              value: "2019-04-07"
                                            }))), React.createElement("div", {
                                      className: "w-full mb-4"
                                    }, React.createElement("div", {
                                          className: "sm:p-3"
                                        }, React.createElement("p", {
                                              className: "text-left pb-2"
                                            }, Utils.str("Location *")), React.createElement("input", {
                                              className: "flex flex-wrap w-full  leading-normal w-px border h-10 border-grey-light rounded px-3  focus:border-blue focus:shadow",
                                              name: "name",
                                              type: "text",
                                              value: "Kenneth Hunt Lawn"
                                            }))), React.createElement("div", {
                                      className: "sm:w-1/2 w-full mb-4"
                                    }, React.createElement("div", {
                                          className: "sm:p-3"
                                        }, React.createElement("p", {
                                              className: "text-left pb-2"
                                            }, Utils.str("Latitude")), React.createElement("input", {
                                              className: "flex flex-wrap w-full  leading-normal w-px border h-10 border-grey-light rounded px-3  focus:border-blue focus:shadow",
                                              name: "name",
                                              placeholder: "Latitude",
                                              type: "number"
                                            }))), React.createElement("div", {
                                      className: "sm:w-1/2 w-full mb-4"
                                    }, React.createElement("div", {
                                          className: "sm:p-3"
                                        }, React.createElement("p", {
                                              className: "text-left pb-2"
                                            }, Utils.str("Longitude")), React.createElement("input", {
                                              className: "flex flex-wrap w-full  leading-normal w-px border h-10 border-grey-light rounded px-3  focus:border-blue focus:shadow",
                                              name: "name",
                                              placeholder: "Longitude",
                                              type: "number"
                                            }))), React.createElement("div", {
                                      className: "w-full mb-4"
                                    }, React.createElement("div", {
                                          className: "sm:p-3"
                                        }, React.createElement("p", {
                                              className: "text-left pb-2"
                                            }, Utils.str("Description")), React.createElement("input", {
                                              className: "flex flex-wrap w-full  leading-normal w-px border h-10 border-grey-light rounded px-3  focus:border-blue focus:shadow",
                                              name: "name",
                                              placeholder: "Description",
                                              type: "text"
                                            }))), React.createElement("div", {
                                      className: "w-full mb-4"
                                    }, React.createElement("div", {
                                          className: "sm:p-3"
                                        }, React.createElement("p", {
                                              className: "text-left pb-2"
                                            }, Utils.str("Facebook link")), React.createElement("input", {
                                              className: "flex flex-wrap w-full  leading-normal w-px border h-10 border-grey-light rounded px-3  focus:border-blue focus:shadow",
                                              name: "name",
                                              placeholder: "Facebook",
                                              type: "text"
                                            }))), React.createElement("div", {
                                      className: "w-full mb-4"
                                    }, React.createElement("div", {
                                          className: "sm:p-3"
                                        }, React.createElement("p", {
                                              className: "text-left pb-2"
                                            }, Utils.str("Image")), React.createElement("input", {
                                              className: "flex flex-wrap w-full  leading-normal w-px border h-10 border-grey-light rounded px-3 pt-1 focus:border-blue focus:shadow",
                                              accept: "image/png, image/jpeg",
                                              name: "name",
                                              type: "file"
                                            }))), React.createElement("div", {
                                      className: "w-full mb-4"
                                    }, React.createElement("div", {
                                          className: "sm:p-3"
                                        }, React.createElement("p", {
                                              className: "text-left pb-2"
                                            }, Utils.str("Tags")), React.createElement("input", {
                                              className: "flex flex-wrap w-full  leading-normal w-px border h-10 border-grey-light rounded px-3  focus:border-blue focus:shadow",
                                              name: "name",
                                              placeholder: "tags",
                                              type: "text"
                                            }))), React.createElement("div", {
                                      className: "flex items-center justify-center w-full"
                                    }, React.createElement("button", {
                                          className: "block bg-orange-dark hover:bg-teal text-white font-bold py-2 px-4 rounded"
                                        }, Utils.str("Update event"))))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
